formation_analytics:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: postgres-dbt
      port: 5432
      user: dbt_user
      pass: dbt_pass
      dbname: analytics
      schema: dev
      
    staging:
      type: postgres
      threads: 4
      host: postgres-dbt
      port: 5432
      user: dbt_user
      pass: dbt_pass
      dbname: analytics
      schema: staging
      
    prod:
      type: postgres
      threads: 8
      host: postgres-dbt
      port: 5432
      user: dbt_user
      pass: dbt_pass
      dbname: analytics
      schema: prod
      
  target: dev